version: '3.8'

services:
  backend:
    build: ./backend  
    image: simple-task-app_backend:latest
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app
    environment:
      - CORS_ORIGINS=http://localhost:3000

  frontend:
    build: ./frontend
    image: simple-task-app_frontend:latest
    ports:
      - "3000:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend 